apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reports-nginx-externalsecret
  namespace: {{ .Values.global.cicd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Replace=true, PruneLast=true
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: reports-nginx-htpasswd
    template:
      metadata:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.devsecops.key }}
