---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  # This is the external image registry (e.g. quay.io/docker)
  name: image-registry-credentials
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Replace=true, PruneLast=true
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: image-registry-credentials
    template:
  dataFrom:
  - extract:
      key: {{ .Values.imageregistrysecret.key }}
