FROM image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

RUN  dnf install -y \
     https://github.com/sigstore/cosign/releases/download/v1.10.0/cosign-1.10.0.x86_64.rpm \
     && dnf clean all 

ENTRYPOINT ["/usr/bin/cosign"]